name: Deploy Extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-extension:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1.4.3

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      
    - name: Install dependencies
      run: npm install
            
    - name: Build extension
      run: npm run extension-build
      
    - name: Create zipped extension
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r extension/pricepointer.zip extension/_dist

    - name: Create extension artifact
      uses: actions/upload-artifact@v2
      with:
        name: extension
        path: extension/pricepointer.zip
